#!/bin/bash

sn-replacestr(){ #@USAGE: value to find
if [ $# -lt 3 ] 
then
printf "USAGE: \$1 value to find,\$2 replace value,\$3 directory\n"
return 0
fi
for i in `grep -Rl $1 $3` 
do 
sed -i "s/$1/$2/g" $i
printf "%s \n" $i
done
}

sn-compress(){
if [ $# -lt 2 ]
then
printf "USAGE: \$1 file or directory name,\$2 gpg file\n"
return 0
fi
tar cj $1 | gpg -e -r public_silgon -o $2
}
sn-ucompress(){
if [ $# -lt 1 ]
then
printf "USAGE: \$1 gpg file\n"
return 0
fi
gpg -d $1 | tar xj
}

sn-alert(){
notify-send "$1" -i ~/Dropbox/design/silgon/logo/logo.png
}
setkb(){
if [ $# -eq 0 ];then
echo "you need arguments"
elif [ $# -eq 1 ]; then
setxkbmap -layout $1
notify-send "Keyboard MSG" "keyboard changed to $1" -u low -i ~/Dropbox/design/silgon/logo/logo.png
elif [ $# -eq 2 ]; then
setxkbmap -layout $1 -variant $2
notify-send "Keyboard MSG" "keyboard changed to $1 - $2" -u low -i ~/Dropbox/design/silgon/logo/logo.png
fi
}
